events { 
    worker_connections 1024; 
}

http {
    # 1. Rate Limiting Setup
    limit_req_zone $binary_remote_addr zone=api_limit_zone:10m rate=10r/s;
    limit_req_status 429;

    # Upstream to NestJS API Gateway (Running inside Docker on Port 3000)
    upstream api_gateway_backend {
        server api-gateway:3000;
    }

    server {
        listen 80;

        # Global CORS Headers
        add_header 'Access-Control-Allow-Origin' 'https://tiny-url-psi.vercel.app' always; # Or '*'
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
        add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization, X-Requested-With' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always; # Mandatoy for HTTP-Only Cookies!

        location / {
            # Apply Rate Limiting
            limit_req zone=api_limit_zone burst=20 nodelay;

            # Handle CORS Preflight natively inside Nginx
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' 'https://tiny-url-psi.vercel.app' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
                add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization, X-Requested-With' always;
                add_header 'Access-Control-Allow-Credentials' 'true' always;
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                add_header 'Content-Length' 0;
                return 204;
            }

            proxy_pass http://api_gateway_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}